apiVersion: apps/v1
kind: Deployment
metadata:
  name: musicapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: musicapi
  template:
    metadata:
      labels:
        app: musicapi
    spec:
      containers:
        - name: musicapi
          image: toanuranjans/musicapi:latest
          ports:
            - containerPort: 5000
          env:
            - name: ASPNETCORE_URLS
              value: 'http://+:5000'
